# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Admin\Desktop\PrimerBuilder\PrimerBuilder.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PrimerBuilder(object):
    def setupUi(self, PrimerBuilder):
        PrimerBuilder.setObjectName("PrimerBuilder")
        PrimerBuilder.resize(647, 580)
        PrimerBuilder.setMinimumSize(QtCore.QSize(647, 580))
        PrimerBuilder.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("H:/LOGO/ksa_logo_TWp_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PrimerBuilder.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(PrimerBuilder)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 11, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_type = QtWidgets.QLabel(self.centralwidget)
        self.label_type.setObjectName("label_type")
        self.horizontalLayout_10.addWidget(self.label_type)
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_10.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_10.addWidget(self.radioButton)
        self.wrn_type = QtWidgets.QLabel(self.centralwidget)
        self.wrn_type.setText("")
        self.wrn_type.setObjectName("wrn_type")
        self.horizontalLayout_10.addWidget(self.wrn_type)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.DNAsequence = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.DNAsequence.setFont(font)
        self.DNAsequence.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DNAsequence.setObjectName("DNAsequence")
        self.horizontalLayout_2.addWidget(self.DNAsequence)
        self.DNAsequence_text = QtWidgets.QTextEdit(self.centralwidget)
        self.DNAsequence_text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.DNAsequence_text.setPlaceholderText("Insert DNA sequence here!")
        self.DNAsequence_text.setObjectName("DNAsequence_text")
        self.horizontalLayout_2.addWidget(self.DNAsequence_text)
        self.DNAsequence_file = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DNAsequence_file.sizePolicy().hasHeightForWidth())
        self.DNAsequence_file.setSizePolicy(sizePolicy)
        self.DNAsequence_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DNAsequence_file.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../.designer/backup/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DNAsequence_file.setIcon(icon1)
        self.DNAsequence_file.setObjectName("DNAsequence_file")
        self.horizontalLayout_2.addWidget(self.DNAsequence_file)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tm = QtWidgets.QLabel(self.centralwidget)
        self.tm.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tm.setObjectName("tm")
        self.horizontalLayout_3.addWidget(self.tm)
        spacerItem1 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.tm_text = QtWidgets.QTextEdit(self.centralwidget)
        self.tm_text.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tm_text.sizePolicy().hasHeightForWidth())
        self.tm_text.setSizePolicy(sizePolicy)
        self.tm_text.setMinimumSize(QtCore.QSize(12, 26))
        self.tm_text.setMaximumSize(QtCore.QSize(30, 27))
        self.tm_text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.tm_text.setWhatsThis("")
        self.tm_text.setObjectName("tm_text")
        self.horizontalLayout_3.addWidget(self.tm_text)
        self.wrn_tm = QtWidgets.QLabel(self.centralwidget)
        self.wrn_tm.setText("")
        self.wrn_tm.setObjectName("wrn_tm")
        self.horizontalLayout_3.addWidget(self.wrn_tm)
        spacerItem2 = QtWidgets.QSpacerItem(285, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ResEnzyme1 = QtWidgets.QLabel(self.centralwidget)
        self.ResEnzyme1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ResEnzyme1.setObjectName("ResEnzyme1")
        self.horizontalLayout_4.addWidget(self.ResEnzyme1)
        spacerItem3 = QtWidgets.QSpacerItem(9, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.ResEnzyme1_text = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResEnzyme1_text.sizePolicy().hasHeightForWidth())
        self.ResEnzyme1_text.setSizePolicy(sizePolicy)
        self.ResEnzyme1_text.setMinimumSize(QtCore.QSize(235, 26))
        self.ResEnzyme1_text.setMaximumSize(QtCore.QSize(67, 26))
        self.ResEnzyme1_text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.ResEnzyme1_text.setObjectName("ResEnzyme1_text")
        self.horizontalLayout_4.addWidget(self.ResEnzyme1_text)
        self.wrn_re1 = QtWidgets.QLabel(self.centralwidget)
        self.wrn_re1.setText("")
        self.wrn_re1.setObjectName("wrn_re1")
        self.horizontalLayout_4.addWidget(self.wrn_re1)
        spacerItem4 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ResEnzyme2 = QtWidgets.QLabel(self.centralwidget)
        self.ResEnzyme2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ResEnzyme2.setObjectName("ResEnzyme2")
        self.horizontalLayout_5.addWidget(self.ResEnzyme2)
        spacerItem5 = QtWidgets.QSpacerItem(9, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.ResEnzyme2_text = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResEnzyme2_text.sizePolicy().hasHeightForWidth())
        self.ResEnzyme2_text.setSizePolicy(sizePolicy)
        self.ResEnzyme2_text.setMinimumSize(QtCore.QSize(67, 26))
        self.ResEnzyme2_text.setMaximumSize(QtCore.QSize(235, 28))
        self.ResEnzyme2_text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.ResEnzyme2_text.setObjectName("ResEnzyme2_text")
        self.horizontalLayout_5.addWidget(self.ResEnzyme2_text)
        self.wrn_re2 = QtWidgets.QLabel(self.centralwidget)
        self.wrn_re2.setText("")
        self.wrn_re2.setObjectName("wrn_re2")
        self.horizontalLayout_5.addWidget(self.wrn_re2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.tag = QtWidgets.QLabel(self.centralwidget)
        self.tag.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tag.setObjectName("tag")
        self.horizontalLayout_7.addWidget(self.tag)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tag_no = QtWidgets.QRadioButton(self.centralwidget)
        self.tag_no.setObjectName("tag_no")
        self.buttonGroup = QtWidgets.QButtonGroup(PrimerBuilder)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.tag_no)
        self.horizontalLayout_6.addWidget(self.tag_no)
        spacerItem8 = QtWidgets.QSpacerItem(32, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.tag_his = QtWidgets.QRadioButton(self.centralwidget)
        self.tag_his.setObjectName("tag_his")
        self.buttonGroup.addButton(self.tag_his)
        self.horizontalLayout_6.addWidget(self.tag_his)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.tag_other = QtWidgets.QRadioButton(self.centralwidget)
        self.tag_other.setObjectName("tag_other")
        self.buttonGroup.addButton(self.tag_other)
        self.horizontalLayout_6.addWidget(self.tag_other)
        self.tag_other_text = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tag_other_text.sizePolicy().hasHeightForWidth())
        self.tag_other_text.setSizePolicy(sizePolicy)
        self.tag_other_text.setMinimumSize(QtCore.QSize(0, 0))
        self.tag_other_text.setMaximumSize(QtCore.QSize(16777215, 26))
        self.tag_other_text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.tag_other_text.setObjectName("tag_other_text")
        self.horizontalLayout_6.addWidget(self.tag_other_text)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sense = QtWidgets.QLabel(self.centralwidget)
        self.sense.setObjectName("sense")
        self.horizontalLayout.addWidget(self.sense)
        self.sense_yes = QtWidgets.QCheckBox(self.centralwidget)
        self.sense_yes.setObjectName("sense_yes")
        self.horizontalLayout.addWidget(self.sense_yes)
        spacerItem10 = QtWidgets.QSpacerItem(24, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.sense_no = QtWidgets.QCheckBox(self.centralwidget)
        self.sense_no.setObjectName("sense_no")
        self.horizontalLayout.addWidget(self.sense_no)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem12 = QtWidgets.QSpacerItem(18, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem12)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.buildPrime = QtWidgets.QPushButton(self.centralwidget)
        self.buildPrime.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.buildPrime.setFont(font)
        self.buildPrime.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buildPrime.setObjectName("buildPrime")
        self.horizontalLayout_8.addWidget(self.buildPrime)

        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        spacerItem15 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem15)
        self.result = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.result.setFont(font)
        self.result.setObjectName("result")
        self.verticalLayout.addWidget(self.result)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.result_text = QtWidgets.QTextEdit(self.centralwidget)
        self.result_text.setMinimumSize(QtCore.QSize(0, 15))
        self.result_text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.result_text.setObjectName("result_text")
        self.horizontalLayout_9.addWidget(self.result_text)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.actionCopy = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionCopy.sizePolicy().hasHeightForWidth())
        self.actionCopy.setSizePolicy(sizePolicy)
        self.actionCopy.setMinimumSize(QtCore.QSize(0, 30))
        self.actionCopy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.actionCopy.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../.designer/backup/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon2)
        self.actionCopy.setObjectName("actionCopy")
        self.verticalLayout_2.addWidget(self.actionCopy)
        self.actionErase = QtWidgets.QPushButton(self.centralwidget)
        self.actionErase.setMinimumSize(QtCore.QSize(0, 30))
        self.actionErase.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.actionErase.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../.designer/backup/broom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionErase.setIcon(icon3)
        self.actionErase.setObjectName("actionErase")
        self.verticalLayout_2.addWidget(self.actionErase)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        spacerItem16 = QtWidgets.QSpacerItem(13, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem16)
        self.credit_1 = QtWidgets.QLabel(self.centralwidget)
        self.credit_1.setObjectName("credit_1")
        self.verticalLayout.addWidget(self.credit_1)
        self.credit_2 = QtWidgets.QLabel(self.centralwidget)
        self.credit_2.setObjectName("credit_2")
        self.verticalLayout.addWidget(self.credit_2)
        PrimerBuilder.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PrimerBuilder)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 647, 26))
        self.menubar.setObjectName("menubar")
        PrimerBuilder.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PrimerBuilder)
        self.statusbar.setObjectName("statusbar")
        PrimerBuilder.setStatusBar(self.statusbar)

        self.retranslateUi(PrimerBuilder)
        QtCore.QMetaObject.connectSlotsByName(PrimerBuilder)




    def retranslateUi(self, PrimerBuilder):
        _translate = QtCore.QCoreApplication.translate
        PrimerBuilder.setWindowTitle(_translate("PrimerBuilder", "PrimerBuilder"))
        self.label_type.setText(_translate("PrimerBuilder", "Input type:"))
        self.radioButton_2.setText(_translate("PrimerBuilder", "DNA"))
        self.radioButton.setText(_translate("PrimerBuilder", "DNAX"))
        self.DNAsequence.setText(_translate("PrimerBuilder", "DNA SEQUENCE"))
        self.tm.setText(_translate("PrimerBuilder", "Tm"))
        self.ResEnzyme1.setText(_translate("PrimerBuilder", "Res Enzyme 1"))
        self.ResEnzyme2.setText(_translate("PrimerBuilder", "Res Enzyme 2"))
        self.tag.setText(_translate("PrimerBuilder", "Tag?"))
        self.tag_no.setText(_translate("PrimerBuilder", "No Tag"))
        self.tag_his.setText(_translate("PrimerBuilder", "His-Tag"))
        self.tag_other.setText(_translate("PrimerBuilder", "Other:"))
        self.tag_other_text.setPlaceholderText(_translate("PrimerBuilder", "Insert custom tag here!"))
        self.sense.setText(_translate("PrimerBuilder", "Tag at sense and/or anti-sense? "))
        self.sense_yes.setText(_translate("PrimerBuilder", "sense"))
        self.sense_no.setText(_translate("PrimerBuilder", "anti-sense"))
        self.buildPrime.setText(_translate("PrimerBuilder", "Build Primer"))
        self.result.setText(_translate("PrimerBuilder", "Result: "))
        self.credit_1.setText(_translate("PrimerBuilder", "PrimerBuilder Reborn v1.2 by Hyunjong Byun powered by SequenceProcessor v2.3 by Hyunjong Byun."))
        self.credit_2.setText(_translate("PrimerBuilder", "GUI design by Minh Hieu (18-206)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PrimerBuilder = QtWidgets.QMainWindow()
    ui = Ui_PrimerBuilder()
    ui.setupUi(PrimerBuilder)
    PrimerBuilder.show()
    sys.exit(app.exec_())

